### ISSUE TITLE
Display UTC time as default

### ISSUE THREAD

**Issue by oskaremil** [timeseriesadmin/timeseriesadmin#2]
When working with time databases, time is of the essence (no pun intended) and converting the timestamps to local time leads to some confusion when inspecting data. 

Using `precision rfc3339` for readability in the command line client may give me a result like this:

```
> SELECT foo FROM database.retention.bar ORDER BY time desc LIMIT 10
name: bar
time                    foo
----                    ---------------
2019-03-06T14:58:16.58Z 12.2525
2019-03-06T14:58:00.58Z 11.804
2019-03-06T14:57:00.58Z 11.3248
2019-03-06T14:56:00.58Z 11.6947
2019-03-06T14:55:00.58Z 11.2338
2019-03-06T14:54:28.58Z 11.3396
2019-03-06T14:54:00.58Z 12.1298
2019-03-06T14:53:48.58Z 12.1635
2019-03-06T14:53:38.58Z 11.9578
2019-03-06T14:53:00.58Z 12.1394
```

The same query in Time Series Admin returns
```

foo |   | 2019-03-06 15:58:16 | 12.2525
foo |   | 2019-03-06 15:58:00 | 11.804
foo |   | 2019-03-06 15:57:00 | 11.3248
foo |   | 2019-03-06 15:56:00 | 11.6947
foo |   | 2019-03-06 15:55:00 | 11.2338
foo |   | 2019-03-06 15:54:28 | 11.3396
foo |   | 2019-03-06 15:54:00 | 12.1298
foo |   | 2019-03-06 15:53:48 | 12.1635
foo |   | 2019-03-06 15:53:38 | 11.9578
foo |   | 2019-03-06 15:53:00 | 12.1394

```

The _Time format_ option should include UTC time formats

**Comment by jmarceli** [comment]
Thanks for reporting that issue. I will try to fix that as soon as possible, hopefully during the upcoming weekend.

**Comment by jmarceli** [comment]
Hi, please download the latest version it should display UTC time instead of a local one.

**Comment by oskaremil** [comment]
Is the docker image updated ?

**Comment by jmarceli** [comment]
Please check the version number, 0.1.3 is the latest. As I checked right now 0.1.3 has a correct time conversion to UTC.

**Comment by oskaremil** [comment]
Thank you


/Oskar Emil Skeide

Den tir. 12. mar. 2019, 21:36 skrev jmarceli <notifications@github.com>:

**Comment by jmarceli** [comment]
Thanks for the confirmation.
