### ISSUE TITLE
Split pannel is not working properly in Mac (ver.0.1.8)

### ISSUE THREAD

**Issue by akrasnov-drv** [timeseriesadmin/timeseriesadmin#242]
If I try to move the middle separator to increase "explore" frame (and accordingly decrease "connection/query" frame) mouse release button event is ignored and the separator keeps moving left and right together with mouse (as if I keep pressing mouse button).
ver. 0.1.8
MacOS 10.15.3 (19D76)

**Comment by jmarceli** [comment]
Thanks for reporting that. I will take a look and release a fix.

**Comment by jmarceli** [comment]
Please check latest release 0.1.9 https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.9

**Comment by akrasnov-drv** [comment]
Do you have MacOS package?

**Comment by jmarceli** [comment]
There was some issue with the uploaded file. Please check once more it should be good now.

**Comment by akrasnov-drv** [comment]
Thank you.
Fixed.

**Comment by jmarceli** [comment]
Thanks for confirmation.
