### ISSUE TITLE
Application is not signed - macOS

### ISSUE THREAD

**Issue by Clovel** [timeseriesadmin/timeseriesadmin#298]
This application is not signed for macOS. It is impossible to run the downloaded app. 

<img width="532" alt="image" src="https://user-images.githubusercontent.com/5107774/80131247-3b071880-859a-11ea-82c8-0cb6c110a91c.png">

**Comment by jmarceli** [comment]
Hi,
I'm not sure if I would be able to sign application without signing to the Apple Developer Program.
Anyway in order to fix you issue you can follow e.g. https://www.howtogeek.com/205393/gatekeeper-101-why-your-mac-only-allows-apple-approved-software-by-default/

**Comment by Clovel** [comment]
Correct, I forgot about that.
