### ISSUE TITLE
Field key requests returns empty

### ISSUE THREAD

**Issue by andersoyvind** [timeseriesadmin/timeseriesadmin#3]
As I navigate my database using the explorer tab, I do not get any output under the measurement's FIELD KEYS list.

![Screenshot from 2019-04-02 14-19-07](https://user-images.githubusercontent.com/2064897/55401936-7af3fb80-5552-11e9-94f2-77239b9fb3e2.png)

I suspect the reason for this is that the query for field keys needs to take the name of the retention policy into account as well.

In the query field, for instance, this works (given correct database is given as connection data).

SHOW FIELD KEYS FROM myRetention.myMeasurement

but this does not:

SHOW FIELD KEYS FROM myMeasurement

The SHOW_FIELD_KEYS database query takes the database and measurement as input, but not the retention policy.

**Comment by jmarceli** [comment]
Hi, thanks for reporting. I will take a closer look at this issue as soon as possible.

**Comment by jmarceli** [comment]
Fixed in a new version ([download v0.1.4](https://timeseriesadmin.github.io/#download)).
Please tell me if it works for you.

**Comment by andersoyvind** [comment]
Works perfectly!

**Comment by jmarceli** [comment]
Thanks confirmation
