### ISSUE TITLE
Port number on server

### ISSUE THREAD

**Issue by gvikram18** [timeseriesadmin/timeseriesadmin#35]
Hi,

I have pulled the deb file of timeseriesadmin and installed it on my ubuntu 18.04 server VM. I dont find instructions on port number on VM server, as in from which port does this application run? I observe a process that is utilising port 8088 after installation, but can't confirm it is timeseriesadmin as my webpage doesn't load

![timeseriesadmin](https://user-images.githubusercontent.com/28858181/70131724-cf82e400-16a8-11ea-80e8-e10896a02c1c.png)

**Comment by jmarceli** [comment]
I'm not sure about your issue. If you downloaded the .deb package you should be able to install it and run like a regular system application. There is no need to open a web browser to use Timeseries Admin installed as a .deb package.
If you are asking about Influx DB database the default port is 8086, so in case you are running InfluxDB locally it should expose its API on `http://localhost:8086` which you can check by entering for example https://status.predictail.com:8086/query?q=SHOW%20DATABASES
Please let me know if this was any help for you.

**Comment by jmarceli** [comment]
Please reopen if any further assistance would be needed.
