### ISSUE TITLE
Is there any option for PROXY setting?

### ISSUE THREAD

**Issue by woohn** [timeseriesadmin/timeseriesadmin#37]
I am trying to use this app in an environment of Proxy. As the company want to bypass any outgoing connection through the proxy server, I have difficulity in finding proxy setting for APP. Do you know how to set proxy information in the app?

**Comment by jmarceli** [comment]
Hi @woohn there is no Proxy settings for this application.
What is exactly behind the mentioned Proxy?
The Influx DB or maybe Timeseries Admin Docker container?
In case of InfluxDB the only way would be exposing its HTTP API on some Proxy port and pass incoming and outgoing traffic through that port or setting up a VPN connection with the server which runs InfluxDB.
Please provide more information, I would be happy to help.

**Comment by jmarceli** [comment]
Hi, regarding PROXY feature, do you think that implementing `proxy` option support from Axios https://github.com/axios/axios#request-config would be any help in your case?
