### ISSUE TITLE
FEATURE: Provide way to adjust the size of the sidebar

### ISSUE THREAD

**Issue by dcj** [timeseriesadmin/timeseriesadmin#4]
When I widen the window of the app, the proportion of space given to the sidebar remains the same.  When using the explorer, I generally need far more width/space for the sidebar than I can currently obtain.

**Comment by jmarceli** [comment]
Thanks for the insight. I will look at this and probably create a new version soon with adjustable sidebar width.

**Comment by jmarceli** [comment]
Resizeable sidebar added in a new version ([download v0.1.4](https://timeseriesadmin.github.io/#download)).
Please tell me if it works for you.

**Comment by dcj** [comment]
Yes, that works well!
Thank you for adding this feature, I really appreciate it.

**Comment by jmarceli** [comment]
Thanks for confirmation
