### ISSUE TITLE
csv export - column with mixed positive and negative numbers has extra quote

### ISSUE THREAD

**Issue by phoebebright** [timeseriesadmin/timeseriesadmin#429]
For example::

    "processed","","2020-06-05 11:00:00","0","EDT2_212550724","EDT2_212550724","CAMU","78.1","116.8","78.1","180.2","36.1","22.2","5"
    "processed","","2020-06-05 11:00:00","'-2","EDT2_212550734","EDT2_212550734","CAMU","96.3","163.5","96.3","230.6","35.6","22.3","9"
    "processed","","2020-06-05 11:00:00","4","EDT2_212550728","EDT2_212550728","CAMU","86.8","144","86.9","194.7","34.8","22.9","9"

Note the column after the date:  ,"0", "'-2", "4" 

Note the extra ' on the negative value.

**Comment by jmarceli** [comment]
Hi, thanks for reporting that issue. I will look at it and let you know when the fix is ready.

**Comment by jmarceli** [comment]
Please check the latest release https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.10 this bug should be fixed now.
