### ISSUE TITLE
SHOW MEASUREMENTS ON databasename-with--

### ISSUE THREAD

**Issue by netbix** [timeseriesadmin/timeseriesadmin#454]
Display error if database name contains the character -  example:  pfsense-ipsec

SHOW MEASUREMENTS ON pfsense-3cx-openvpn

400: Bad Request
Error details

You should probably look at "response" key

Error {config: Object, request: XMLHttpRequest, response: Object, isAxiosError: true, toJSON: ƒ ()}

config: Object

url: "http://192.168.0.25:8086/query"

method: "post"

params: Object

data: "q=SHOW%20MEASUREMENTS%20ON%20pfsense-3cx-openvpn"

headers: Object

auth: Object

transformRequest: Array(1)

transformResponse: Array(1)

timeout: 0

adapter: ƒ ()

xsrfCookieName: "XSRF-TOKEN"

xsrfHeaderName: "X-XSRF-TOKEN"

maxContentLength: -1

validateStatus: ƒ validateStatus()

unsafeSsl: ""

    __typename: "FormData"

request: XMLHttpRequest

response: Object

data: "error "error parsing query: found -, expected ; at line 1, char 29" "

status: 400

statusText: "Bad Request"

headers: Object

config: Object

    request: XMLHttpRequest

isAxiosError: true

toJSON: ƒ ()

![immagine](https://user-images.githubusercontent.com/66208491/90957713-ca143680-e48f-11ea-97be-64e8c9a8bfba.png)

**Comment by jmarceli** [comment]
Hi @netbix,
Thanks for reporting that issue. Please check newest version https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.11

**Comment by netbix** [comment]
Perfect ! I have test windows and docker !
![immagine](https://user-images.githubusercontent.com/66208491/90986071-83ead000-e580-11ea-8723-94f5a0bf8f68.png)

thank you
