### ISSUE TITLE
Tags and fields with dots don't show their values

### ISSUE THREAD

**Issue by etricky** [timeseriesadmin/timeseriesadmin#463]
Hello

I'm using ver. 0.1.12 and in my database I have some tags and fields that have "." in their names, for example, "diff.day". When I run a query, the values of these columns are never displayed as you can see in the below picture.

![image](https://user-images.githubusercontent.com/6766415/93010769-ce5fdb00-f587-11ea-9a5e-d325309ea82a.png)

value and "diff.day" are fields and "tag.day" and "year" are tags. The ones with the dots in the name don't show any value but, as you can see in the query, I can use their values to filter in the where clause and in the explorer tab, for the tags, it shows the list of values they contain. I also know that these fields/tags have values because, if I do a query using a java program, I do get the results I'm expecting.

![image](https://user-images.githubusercontent.com/6766415/93010826-77a6d100-f588-11ea-927c-d6dac65c677b.png)

**Comment by jmarceli** [comment]
Hi @etricky  thanks for reporting that. I will let you know when fix is ready.

**Comment by jmarceli** [comment]
It turns out to be an issue of the underlaying tables library https://github.com/gregnb/mui-datatables/issues/909 . I have updated the dependency and as far as I can test it is ok right now. Please update to v0.1.13 (https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.13) and confirm if that fix the issue.

**Comment by etricky** [comment]
@jmarceli I can confirm the issue is resolved. Thanks for the quick fix, I really appreciate it.
