### ISSUE TITLE
Raspi arm build ?

### ISSUE THREAD

**Issue by tablatronix** [timeseriesadmin/timeseriesadmin#480]
Anyone build this docker, for arm ?

**Comment by mlittle** [comment]
would love to see an arm build as well.  wasn’t obvious to me how to build an arm version either. :(

**Comment by codersaur** [comment]
Plus one for an arm64 docker!

**Comment by tablatronix** [comment]
> Plus one for an arm64 docker!

Isn't that the same thing?

**Comment by codersaur** [comment]
Sorry, "plus one" as in "another vote for"...

**Comment by tablatronix** [comment]
Hah gotcha

**Comment by jmarceli** [comment]
Hi, please try this one `docker pull timeseriesadmin/timeseriesadmin:0.1.13-multiplatform-dev.0` https://hub.docker.com/r/timeseriesadmin/timeseriesadmin/tags?page=1&ordering=last_updated and let me know if it works as I don't have any testing environment for that.
I've never publish any multi-platform Docker images before, so I'm counting on your help and feedback.
If it will work I can extend my release pipeline with multi-platform builds as it seems to be pretty straight forward.
For my own reference here are the commands which I used to build this one:
```
docker buildx create --use
docker buildx build  --platform linux/amd64,linux/arm64,linux/arm/v7 -t timeseriesadmin/timeseriesadmin:0.1.13-multiplatform-dev.0 --push .
```
If it will work maybe I will be able to help with https://github.com/timeseriesadmin/timeseriesadmin/issues/470 as well

**Comment by mlittle** [comment]
@jmarceli the arm build works perfectly.  was able to pull that docker and publish no issue.  Works great on my raspberry pi4.  Thanks!

**Comment by tablatronix** [comment]
It runs, have not tested yet but it works!

EDIT: I can connect and see databases, looks good

**Comment by jmarceli** [comment]
I'm glad to hear that. I will include multi-platform builds to the next releases.
