### ISSUE TITLE
unsafeSsl is not supported

### ISSUE THREAD

**Issue by liangxinhui** [timeseriesadmin/timeseriesadmin#5]
My InfluxDB is configured with ssl enabled.

The configure of `Time Series Admin` is:

- Database URL: https://10.x.x.x:8086
- User: ********
- Password:••••••••••
- Database: telegraf

and Errors:

<pre>
400:Network Error This might be a CORS error, network problem or invalid HTTPS redirect, invalid URL. Please check your connection configuration once more.
Error details
You should probably look at "response" key
t {	graphQLErrors: Array[0], networkError: Object, extraInfo: Error}
	graphQLErrors: Array[0]
	networkError: Object
	extraInfo: Error
		config: Object
			adapter: function ()
			transformRequest: Object
			0: function ()
			transformResponse: Object
			0: function ()
			timeout: 0
			xsrfCookieName: "XSRF-TOKEN"
			xsrfHeaderName: "X-XSRF-TOKEN"
			maxContentLength: -1
			validateStatus: function validateStatus()
			headers: Object
			method: "post"
			url: "https://10.x.x.x:8086/query"
			auth: Object
			data: "q=show%20databases"
			params: Object
		request: XMLHttpRequest
		response: Object
			status: 400
			statusText: "Network Error"
			data: "This might be a CORS error, network problem or invalid HTTPS redirect, invalid URL. Please check your connection configuration once more."
;
</pre>

While，the `influx` command with parameters below is successful:

```bash
influx -host '10.x.x.x' -port '8086' -database telegraf -username **** -password **** -ssl -unsafeSsl -execute "show databases"
```

The `[http]` configuration in `/etc/influxdb/influxdb.conf`

```
[http]
  auth-enabled = true
  https-enabled = true
  https-certificate = "/etc/ssl/my-selfsigned.crt"
  https-private-key = "/etc/ssl/my-selfsigned.key"
```

**Comment by jmarceli** [comment]
Did you try using non-ssl URL http://10.x.x.x:8086 in configuration settings?

**Comment by liangxinhui** [comment]
> Did you try using non-ssl URL http://10.x.x.x:8086 in configuration settings?

Yes， same error as https.

**Comment by jmarceli** [comment]
What happens if you enter https://10.x.x.x:8086/query?q=show%20databases directly from the browser? Do you see any results?

I'm asking because that's exactly how this application works.

**Comment by liangxinhui** [comment]
> What happens if you enter https://10.x.x.x:8086/query?q=show%20databases directly from the browser? Do you see any results?
> 
> I'm asking because that's exactly how this application works.

I try it  with `Chrome`, the result is :

![QQ截图20191127084428](https://user-images.githubusercontent.com/2174869/69684068-16456c80-10f2-11ea-91e2-8d2440f48d07.png)

**Comment by liangxinhui** [comment]
I'm not familiar with `node.js` or `electron`, but this might be useful:

https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

https://stackoverflow.com/questions/44658269/electron-how-to-allow-insecure-https/50419166

**Comment by jmarceli** [comment]
Thanks for the detailed description and reference links. I will try to add ignore SSL errors checkbox to the next release which I would like to roll out during the upcoming weekend.

**Comment by liangxinhui** [comment]
Looking forward to this new feature.

Thanks!

**Comment by jmarceli** [comment]
I've investigated that issue further. Currently, all requests are executed directly from the browser which is convenient as it behaves in a similar way regardless if you run the application through the Electron or via Docker container (directly in the browser).

First of all please let me know if you are using Docker image or Electron app?

In case of Docker image (and generally usage through your system browser) I'm not able to help, but you should be able set this up inside your browser preferences/settings in Google Chrome it might be similar to https://superuser.com/questions/27268/how-do-i-disable-the-warning-chrome-gives-if-a-security-certificate-is-not-trust.

For Electron App version I will be probably able to provide some workaround but it will take some time to develop this as it requires redirecting all the requests to the Electron.

**Comment by liangxinhui** [comment]
Either `Docker` or `Electron`  is OK.

Could you please tell me some detail of the Docker solution, For the following scenarios:

- Docker image running on  `server-docker`
- target influxdb server is `server-db`
- My PC is the `client`

When I connect the `server-db` via `server-docker`'s web page,  where is the bottleneck?

`client to server-db` or `server-db to server-db`?

In other words, whose connection is blocked? `client` or `server-docker`?

I have tried some solutions from https://superuser.com/questions/27268/how-do-i-disable-the-warning-chrome-gives-if-a-security-certificate-is-not-trust, but it seems not working.

Thanks again. 

Enjoy your time, i am not in a hurry.

**Comment by jmarceli** [comment]
In a new version [0.1.5](https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.5) I've added support for unsafe SSL in Electron Application. Please let me know if it is working for you.

**Comment by liangxinhui** [comment]
Awesome,  the `Ignore SSL errors` feature  works really well in Electron ( version 0.1.6 ).

**Comment by jmarceli** [comment]
Thanks for the feedback

**Comment by fedorkotov** [comment]
`Ignore SSL errors` flag is ignored by `Explorer` panel in v0.1.7 electron app
![image](https://user-images.githubusercontent.com/1106650/73092534-dd592680-3eed-11ea-912a-b7e7a13c5def.png)
I filled in "URL", "User", "Password" and "Database" fields, set "Ignore SSL Errors" flag and clicked on "Save Connection Data" button.
I can execute queries but can not use Explorer. Full test of error message in Explorer tab is
```
{"details":"Error: unable to verify the first certificate\n at TLSSocket.onConnectSecure (_tls_wrap.js:1317:34)\n at TLSSocket.emit (events.js:203:13)\n at TLSSocket._finishInit (_tls_wrap.js:792:8)\n at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:606:12)","isCommon":true,"title":"UNABLE_TO_VERIFY_LEAF_SIGNATURE: unable to verify the first certificate"}
```

My InfluxDB server uses certificate signed by my own certificate authority and my OS is Ubuntu 18.04.

**Comment by jmarceli** [comment]
Hi,
Thanks for the feedback. Please check the latest release https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.8

**Comment by fedorkotov** [comment]
I updated to v0.1.8 and now I can both execute queries and use Explorer panel. Thank you for the fix.

**Comment by jmarceli** [comment]
Thanks for the confirmation.
