### ISSUE TITLE
decrease row height

### ISSUE THREAD

**Issue by anatolijd** [timeseriesadmin/timeseriesadmin#57]
hi Jan,

I'd like to make results table more condensed, i.e.   decrease row height, so I can see more rows on a page.  How can I do that ?

**Comment by jmarceli** [comment]
As for now, it is not a configurable option. I think about that feature for the next release. I will let you know when it will be available

**Comment by jmarceli** [comment]
Please check the latest v0.1.7 release with condensed layout support https://github.com/timeseriesadmin/timeseriesadmin/releases/tag/v0.1.7 and let me know how do you like it.
