### ISSUE TITLE
Not working on Raspberry pi4 with Bullseye?

### ISSUE THREAD

**Issue by pvdlind** [timeseriesadmin/timeseriesadmin#602]
Hi,
I'm trying to install timeseriesadmin on a Raspberry Pi4 with Bulleye to monitor a InfluxDB database.
I get this error:
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested.
Is there a solution?
Thx,
Peter.

**Comment by jmarceli** [comment]
Hi @pvdlind,
How do you install timeseriesadmin? I assume that this is through Docker then you should be able to select the right image for your platform that is https://hub.docker.com/layers/timeseriesadmin/timeseriesadmin/timeseriesadmin/0.1.13-multiplatform-dev.0/images/sha256-b38a70d59bf26ada83c69e77ba21fdbb1ef9aa31af53db3075d4982c94504aae?context=explore
Please let me know if it helps.
You can also browse https://github.com/timeseriesadmin/timeseriesadmin/issues/480 and possibly ask there as it seems that  it should be working on Raspberry pi4.
