### ISSUE TITLE
Columns are not parsed correct when using ORDER BY time DESC

### ISSUE THREAD

**Issue by oskaremil** [timeseriesadmin/timeseriesadmin#61]
This query

```
select * from db.ret.em_telemetry order by time asc limit 100
```

returns these colums
![image](https://user-images.githubusercontent.com/1819584/70603690-60047b80-1bf7-11ea-8932-9dffbb446a60.png)

If I want to order by time it seems like Time Series Admin can not properly parse the response:

```
select * from db.ret.em_telemetry order by time desc limit 100
```

![image](https://user-images.githubusercontent.com/1819584/70603868-c4273f80-1bf7-11ea-8b3e-ba70a8b3f505.png)

**Comment by jmarceli** [comment]
I will look at this as soon as possible

**Comment by jmarceli** [comment]
Unfortunately, I was unable to reproduce this bug. Maybe you can check the results of a direct query from the browser? There should be some (significant) differences in response. Generally Time Series Admin gets data in CSV format from InfluxDB API and then pass it to Papaparse (https://www.papaparse.com/) and parsed results are presented through https://github.com/gregnb/mui-datatables
