### ISSUE TITLE
Compatible to InfluxDB v2.3?

### ISSUE THREAD

**Issue by jayjupdhig** [timeseriesadmin/timeseriesadmin#611]
Hi

Is it compatible to InfluxDB v2.3?

Best regards, Patrick

**Comment by jmarceli** [comment]
Hi @jayjupdhig,
It should be compatible (based on the docs https://docs.influxdata.com/influxdb/v2.3/query-data/influxql/)  but it wasn't ever tested.
Please note that only InfluxQL queries are supported.
